security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        users:
            entity:
                class:    'AppBundle\Entity\User'
                property: 'username'

    firewalls:
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        default:
            pattern:    ^/
            anonymous:  ~
            form_login: ~
            logout:     ~
