app_homepage:
    #    path:     /hello/{name}
    #    defaults: { _controller: AppBundle:Default:index }
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AppBundle:Default:index.html.twig'

account_register:
    path: /register
    defaults:
        _controller: AppBundle:Account:register
